# Generated by Django 3.1.4 on 2020-12-27 13:09

from django.db import migrations
import memories.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='address',
            field=memories.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='geolocation',
            field=memories.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
