# Generated by Django 3.1.4 on 2020-12-28 07:25

from django.db import migrations, models
import memories.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20201227_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='img_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='address',
            field=memories.fields.AddressField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='geolocation',
            field=memories.fields.GeoLocationField(max_length=100, null=True, verbose_name='Координаты'),
        ),
    ]
