# Generated by Django 3.1.4 on 2020-12-28 08:14

from django.db import migrations
import memories.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_auto_20201228_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='geolocation',
            field=memories.fields.GeoLocationField(max_length=100, null=True, verbose_name=''),
        ),
    ]
